- Reference
  - https://blog.amedama.jp/entry/2019/01/29/235642

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
import xgboost as xgb

In [3]:
dataset = datasets.load_breast_cancer()
X, y = dataset.data, dataset.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, shuffle=True, random_state=42, stratify=y)

In [4]:
print(X_train.shape, y_train.shape)

(398, 30) (398,)


In [5]:
X_train[0]

array([1.162e+01, 1.818e+01, 7.638e+01, 4.088e+02, 1.175e-01, 1.483e-01,
       1.020e-01, 5.564e-02, 1.957e-01, 7.255e-02, 4.101e-01, 1.740e+00,
       3.027e+00, 2.785e+01, 1.459e-02, 3.206e-02, 4.961e-02, 1.841e-02,
       1.807e-02, 5.217e-03, 1.336e+01, 2.540e+01, 8.814e+01, 5.281e+02,
       1.780e-01, 2.878e-01, 3.186e-01, 1.416e-01, 2.660e-01, 9.270e-02])

In [11]:
y_train[:10]

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [6]:
type(dataset)

sklearn.utils.Bunch

In [9]:
dataset.target_names

array(['malignant', 'benign'], dtype='<U9')

In [12]:
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [13]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

In [16]:
print(dtrain.feature_names)

['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29']


In [17]:
print(dtrain.num_col, dtrain.num_col)

<bound method DMatrix.num_col of <xgboost.core.DMatrix object at 0x1208e0ac8>> <bound method DMatrix.num_col of <xgboost.core.DMatrix object at 0x1208e0ac8>>


In [19]:
xgb_params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
}

bst = xgb.train(xgb_params,
                dtrain,
                num_boost_round=100,)

In [20]:
y_pred_proba = bst.predict(dtest)

In [22]:
print(y_pred_proba[:10])

[1.1187010e-02 9.9191225e-01 9.8089212e-01 7.1520073e-04 3.6118871e-01
 5.3184619e-04 9.9880350e-01 2.1883224e-03 9.9924409e-01 4.6064783e-04]


In [23]:
y_pred = np.where(y_pred_proba > 0.5, 1, 0)

In [24]:
print(y_pred[:10])

[0 1 1 0 0 0 1 0 1 0]


In [25]:
acc = accuracy_score(y_test, y_pred)
print('Accuracy:', acc)

Accuracy: 0.9649122807017544


In [26]:
print(len(y_test), len(y_pred))

171 171
