- Reference
  - https://lightgbm.readthedocs.io/en/latest/Python-Intro.html

In [2]:
import numpy as np

In [6]:
import lightgbm as lgb

In [7]:
#train_data = lgb.Dataset('train.svm.bin')

In [8]:
data = np.random.rand(500, 10)
label = np.random.randint(2, size=500)
train_data = lgb.Dataset(data, label=label)

In [9]:
data.shape

(500, 10)

In [10]:
data

array([[0.07735583, 0.82303398, 0.62206188, ..., 0.99074797, 0.44208812,
        0.98991005],
       [0.65783164, 0.58778008, 0.63011512, ..., 0.30767858, 0.08061087,
        0.70839148],
       [0.06354966, 0.05721103, 0.49279591, ..., 0.62933701, 0.01197158,
        0.96877477],
       ...,
       [0.55469197, 0.41155858, 0.05964176, ..., 0.18497415, 0.91921303,
        0.51649815],
       [0.0589261 , 0.6649454 , 0.98338213, ..., 0.1845339 , 0.2035213 ,
        0.70972796],
       [0.07666999, 0.71691207, 0.30167829, ..., 0.68353651, 0.698     ,
        0.82549821]])

In [11]:
label.shape

(500,)

In [12]:
label

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [13]:
train_data

In [17]:
#train_data.label
#train_data.feature_name
train_data.get_data

<bound method Dataset.get_data of <lightgbm.basic.Dataset object at 0x12962dcc0>>

In [19]:
# import scipy
# csr = scipy.sparse.csr_matrix((dat, (row, col)))
# train_data = lgb.Dataset(csr)

In [21]:
#train_data = lgb.Dataset('train.svm.txt')
train_data.save_binary('data/train.bin')

In [29]:
#validation_data = train_data.create_valid('validation.svm')
#validation_data = lgb.Dataset('data/validation.svm', reference=train_data)
data2 = np.random.rand(100, 10)
label2 = np.random.randint(2, size=100)
validation_data = lgb.Dataset(data2, label=label2, reference=train_data)

In [30]:
validation_data

In [31]:
#train_data = lgb.Dataset(data, label=label, feature_name=['c1', 'c2', 'c3'], categorical_feature=['c3'])

In [32]:
# w = np.random.rand(500, )
# train_data = lgb.Dataset(data, label=label, weight=w)

#train_data = lgb.Dataset(data, label=label)
w = np.random.rand(500, )
train_data.set_weight(w)

In [33]:
param = {'num_leaves': 31, 'objective': 'binary'}
#param['metric'] = 'auc'
param['metric'] = ['auc', 'binary_logloss']

In [34]:
num_round = 10

bst = lgb.train(param, train_data, num_round, valid_sets=[validation_data])

[1]	valid_0's auc: 0.516058	valid_0's binary_logloss: 0.69646
[2]	valid_0's auc: 0.501807	valid_0's binary_logloss: 0.698757
[3]	valid_0's auc: 0.495383	valid_0's binary_logloss: 0.701811
[4]	valid_0's auc: 0.479326	valid_0's binary_logloss: 0.710317
[5]	valid_0's auc: 0.492573	valid_0's binary_logloss: 0.710346
[6]	valid_0's auc: 0.483541	valid_0's binary_logloss: 0.713193
[7]	valid_0's auc: 0.478723	valid_0's binary_logloss: 0.720273
[8]	valid_0's auc: 0.467483	valid_0's binary_logloss: 0.724377
[9]	valid_0's auc: 0.48876	valid_0's binary_logloss: 0.722143
[10]	valid_0's auc: 0.493577	valid_0's binary_logloss: 0.722172


In [35]:
bst.save_model('data/model.txt')

In [36]:
json_model = bst.dump_model()

In [38]:
#json_model

In [39]:
bst = lgb.Booster(model_file='data/model.txt')

In [40]:
lgb.cv(param, train_data, num_round, nfold=5)

{'auc-mean': [0.5193471966026215,
  0.4943458355683453,
  0.49452384093133556,
  0.4830471275640894,
  0.47676676775331994,
  0.47532574157432794,
  0.47215372020913426,
  0.4749107153227114,
  0.4749193675814909,
  0.4625497720288477],
 'auc-stdv': [0.06626191354033013,
  0.07731035635852117,
  0.0814713307563419,
  0.09035275690935578,
  0.08285271428837633,
  0.08041551953319719,
  0.07914184716804541,
  0.0926299003030456,
  0.09142558422606097,
  0.08873130872259317],
 'binary_logloss-mean': [0.69244405776717,
  0.6956729651419681,
  0.6991192018947677,
  0.7035156446429781,
  0.7092620604304869,
  0.7141978301004526,
  0.7191848924619569,
  0.721632836512653,
  0.7264821125967785,
  0.7353982722965271],
 'binary_logloss-stdv': [0.006387759519872379,
  0.010596523177357849,
  0.01637831748481839,
  0.022612658861444798,
  0.02447325566429513,
  0.027521883475263697,
  0.031475200841147584,
  0.038510216710653807,
  0.03973918075229783,
  0.044116849407914945]}

In [42]:
#bst = lgb.train(param, train_data, num_round, valid_sets=valid_sets, early_stopping_rounds=5)
bst = lgb.train(param, train_data, num_round, valid_sets=[validation_data], early_stopping_rounds=5)
bst.save_model('data/model.txt', num_iteration=bst.best_iteration)

[1]	valid_0's auc: 0.516058	valid_0's binary_logloss: 0.69646
Training until validation scores don't improve for 5 rounds
[2]	valid_0's auc: 0.501807	valid_0's binary_logloss: 0.698757
[3]	valid_0's auc: 0.495383	valid_0's binary_logloss: 0.701811
[4]	valid_0's auc: 0.479326	valid_0's binary_logloss: 0.710317
[5]	valid_0's auc: 0.492573	valid_0's binary_logloss: 0.710346
[6]	valid_0's auc: 0.483541	valid_0's binary_logloss: 0.713193
Early stopping, best iteration is:
[1]	valid_0's auc: 0.516058	valid_0's binary_logloss: 0.69646


In [43]:
data = np.random.rand(7, 10)
ypred = bst.predict(data)

In [44]:
ypred

array([0.4926498 , 0.47996423, 0.51629946, 0.50214743, 0.54187133,
       0.48095678, 0.52213838])

In [45]:
ypred = bst.predict(data, num_iteration=bst.best_iteration)
ypred

array([0.4926498 , 0.47996423, 0.51629946, 0.50214743, 0.54187133,
       0.48095678, 0.52213838])